### PR TITLE
Extracting part that generates full URL into it's own method so that …

### PR DESCRIPTION
**Pull request by awesomeousPrime**
Extracting part of method which generates full URL of an item. 

For example: 

```html
<a href="/testing.php">Testing</a>
<!-- Not sure if the site below is real this is just for demonstration purposes...Not responsible for any material encountered -->
<a href="https://www.flexiblemink.com/testing>Testing</a>
```

With this, both of these href attributes would generate a full URL in the case of the first example, the current url would be used so if a person is on `https://www.stdcheck.com/adslkjfsl`

the url would be https://www.stdcheck.com/testing.php

The second example should just generate what is passed in as is since it's a full path already.

### CODE REVIEW

**Comment by awesomeousPrime** [comment]
!force code review

**Comment by medology-bugman** [comment]
Paging @RedEnchilada to review the back-end work in this pull request!

**Comment by RedEnchilada** [comment]
Your example is not syntactically valid because you're missing a quotation mark.

**Comment by RedEnchilada** [comment]
👍  6577f08

**Comment by awesomeousPrime** [comment]
submitting separate pull request for the changes mentioned in CR :P

**Pull request merged**
