### PR TITLE
When asserting page contains text, injectStoredValues to be able to r…

### PR DESCRIPTION
**Pull request by awesomeousPrime**
Adding the use of injectStoredValues into assertPageContainsText

### CODE REVIEW

**Comment by medology-bugman** [comment]
Paging @hopeseekr to review the back-end work in this pull request!

**Comment by hopeseekr** [comment]
!reassign testing @Chekote

**Comment by medology-bugman** [comment]
Paging @Chekote to review the testing work in this pull request!

**Comment by Chekote** [comment]
e5703ba is good to merge.

**Pull request merged**
