### PR TITLE
Creating Method to Assert Element is not Covered by Another 

### PR DESCRIPTION
**Pull request by awesomeousPrime**
Adding a method to assert that an element is not being covered by another.

This method gets the surrounding square space of an item and checks points on the item and compares them to the element being tested. If there is an item that is found to be different, than the one specified, an exception is thrown.

A simple test was added to assert that the assertion is working as intended.

Another pull request exists for adding this in 1.0 also [here](https://github.com/Medology/FlexibleMink/pull/198)

### CODE REVIEW

**Comment by awesomeousPrime** [comment]
!reassign front-end @johnnie502

**Comment by healthlabs-bugman** [comment]
Paging @johnnie502 to review the front-end work in this pull request!

**Comment by awesomeousPrime** [comment]
!reassign back-end @RedEnchilada

**Comment by healthlabs-bugman** [comment]
Paging @RedEnchilada to review the back-end work in this pull request!

**Comment by awesomeousPrime** [comment]
!reassign testing @fortoulrodolfo

**Pull request merged**
