### PR TITLE
Apply fixes from StyleCI

### PR DESCRIPTION
**Pull request by johnnie502**
This pull request applies code style fixes from an analysis carried out by [StyleCI](https://styleci.io).

---

For more information, click [here](https://styleci.io/analyses/XVj5NV).

### CODE REVIEW

**Comment by medology-bugman** [comment]
Paging @RedEnchilada to review the back-end work in this pull request!

**Comment by RedEnchilada** [comment]
🙆

**Comment by johnnie502** [comment]
❓

**Comment by RedEnchilada** [comment]
⛸

**Pull request merged**
